#!/usr/bin/env bash
set -euo pipefail

# Generated by jlo setup
# Do not edit manually - regenerate with 'jlo setup gen'


# ==============================================================================
# Install GitHub CLI
# ==============================================================================

if command -v gh >/dev/null 2>&1; then
  echo "gh already installed: $(gh --version | head -1)"
  exit 0
fi

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "Unsupported platform for automated gh install: $(uname -s). Install gh manually." >&2
  exit 1
fi

if ! command -v apt-get >/dev/null 2>&1; then
  echo "apt-get is required to install gh automatically. Install gh manually for this environment." >&2
  exit 1
fi

install_gh_from_official_repo() {
  apt-get update
  apt-get install -y --no-install-recommends ca-certificates curl gnupg

  mkdir -p -m 755 /etc/apt/keyrings
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
    -o /etc/apt/keyrings/githubcli-archive-keyring.gpg
  chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg

  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
    > /etc/apt/sources.list.d/github-cli.list

  apt-get update
  apt-get install -y --no-install-recommends gh
}

if [[ "$(id -u)" -eq 0 ]]; then
  install_gh_from_official_repo
elif command -v sudo >/dev/null 2>&1; then
  sudo bash -lc "$(declare -f install_gh_from_official_repo); install_gh_from_official_repo"
else
  echo "Root or sudo is required to install gh with apt-get. Install gh manually." >&2
  exit 1
fi

gh --version

# ==============================================================================
# Install just - command runner
# ==============================================================================

if command -v just >/dev/null 2>&1; then
  installed_version="$(just --version | awk '{print $2}')"
  requested_version="${JUST_VERSION#v}"
  if [[ -z "${JUST_VERSION:-}" || "$installed_version" == "$requested_version" ]]; then
    echo "just already installed: $(just --version)"
    exit 0
  fi
fi

mkdir -p "$HOME/.local/bin"
export PATH="$HOME/.local/bin:$PATH"

if [[ -n "${JUST_VERSION:-}" ]]; then
  if ! command -v tar >/dev/null 2>&1; then
    echo "tar is required for version-pinned just installation." >&2
    exit 1
  fi

  version="${JUST_VERSION#v}"
  arch="$(uname -m)"
  case "$arch" in
    x86_64) target="x86_64-unknown-linux-musl" ;;
    aarch64|arm64) target="aarch64-unknown-linux-musl" ;;
    *)
      echo "Unsupported architecture for JUST_VERSION install: $arch" >&2
      exit 1
      ;;
  esac

  tmp_dir="$(mktemp -d)"
  trap 'rm -rf "$tmp_dir"' EXIT
  archive="$tmp_dir/just.tgz"
  curl --proto '=https' --tlsv1.2 -fsSL \
    "https://github.com/casey/just/releases/download/${version}/just-${version}-${target}.tar.gz" \
    -o "$archive"
  tar -xzf "$archive" -C "$tmp_dir"
  install -m 0755 "$tmp_dir/just" "$HOME/.local/bin/just"
else
  curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh \
    | bash -s -- --to "$HOME/.local/bin"
fi

just --version

# ==============================================================================
# Project-specific post-install hook
# ==============================================================================
#
# Example:
# if command -v just >/dev/null 2>&1; then
#   just setup
# fi
