name: CI Workflows

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint and Typecheck
    uses: ./.github/workflows/run-linters.yml

  test:
    name: Test
    uses: ./.github/workflows/run-tests.yml

  verify-dist:
    name: Verify Dist
    uses: ./.github/workflows/verify-dist.yml
