name: CI Workflows

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref || github.ref }}
  cancel-in-progress: true

jobs:
  static-checks:
    name: Static Checks
    uses: ./.github/workflows/run-static-checks.yml

  test:
    name: Test
    uses: ./.github/workflows/run-tests.yml
